### ISSUE TITLE
Plain d3.js usage

### ISSUE THREAD

**Issue by kuldarim** [d3fc/d3fc-discontinuous-scale#21]
Is it possible to use this custom scale with plain d3.js or there is a dependency on d3fc so it also needs to be included?

**Comment by ColinEberhardt** [comment]
d3fc is assembled from a number of smaller components. You don't have to use all of d3fc (i.e. the top-level bundle) in order to use specific component. However, it may have some dependencies on other d3fc components.

This scale has a dependency on d3fc-rebind, as shown here:

https://github.com/d3fc/d3fc-discontinuous-scale/blob/master/package.json#L25

If you are using some form of bundler (webpack, rollup), it should resolve these dependencies for you. 

if not, you can just include the dependencies directly. Using the unpkg CDN, this should do the trick:

```
<script src="https://unpkg.com/d3@4.8.0"></script>
<script src="https://unpkg.com/d3fc-rebind@4.1.1"></script>
<script src="https://unpkg.com/d3fc-discontinuous-scale@2.0.3"></script>
```

**Comment by kuldarim** [comment]
What about versions compatibility? Is it only usable with v4 or I can also use it with v3?

**Comment by chrisprice** [comment]
I don't think the scale "interface" changed between v3 & v4 so you should be fine with either.

**Comment by kuldarim** [comment]
Thanks, I have checked and it seems to be working with either d3 v3 or v4 without dependencies on d3fc core. So I'm closing this topic. 

BTW great job guys, that discontinuous scale is really useful thing.
